'use strict';

// The launcher's own tests. `npm test` runs these, and CI runs `npm test` in the Node job.
//
// 0.6.10 REWROTE THESE. The previous version asserted one thing — that the install pinned the npm
// package's version — and the launcher satisfied it by running `pip install` into whichever
// interpreter it found. That is refused by PEP 668 on Homebrew Python, Debian's python3 and most
// distribution builds, so `npx bounded-loops` was broken on a stock macOS machine while this test
// stayed green: the fake python3 shim below happily "succeeded" at a pip install that a real managed
// interpreter refuses. A shim that accepts what production rejects is a test that cannot see the bug.
//
// So these tests now assert the RESOLUTION ORDER, not just the pin: an already-matching interpreter
// wins, then a matching `bl` on PATH, and only then a private virtual environment. And they assert
// the install never targets the discovered interpreter.
//
// The old test also let the launcher write into the caller's real ~/.cache. Every case here sets
// BOUNDED_LOOPS_NPM_HOME to a temp directory.

const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const test = require('node:test');

const launcher = path.resolve(__dirname, '..', 'bin', 'bounded-loops.js');
// Derived, never hardcoded: parity with package.json is the claim, so reading it is what proves it
// and is what stops this rotting on the next version bump.
const { version: packageVersion } = require('../package.json');

function workspace() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'bounded-loops-npm-test-'));
}

// A fake `python3` on an otherwise-empty PATH. `reports` is what it claims is installed; passing
// null means "no engine installed". Everything it is asked is appended to the log, which is what the
// assertions read. `-m venv <root>` materialises a second shim at <root>/bin/python that reports the
// package version, so the managed-venv path can be exercised without a real interpreter.
function fakePython(dir, { reports }) {
  const target = path.join(dir, 'python3');
  const version = reports === null ? '' : reports;

  // The interpreter a created venv would expose. Written as its own FILE and copied by the shim,
  // rather than generated by nested printf inside it — the first version of this test built it with
  // escaped printf and produced a broken script, so the venv path silently fell through to the
  // give-up branch and three tests failed for a reason that had nothing to do with the launcher.
  fs.writeFileSync(
    path.join(dir, 'venv-python-template'),
    '#!/bin/sh\n' +
      'printf "venv: %s\\n" "$*" >> "$BOUNDED_LOOPS_TEST_LOG"\n' +
      'case "$*" in\n' +
      `  *importlib.metadata*) printf '${packageVersion}\\n'; exit 0 ;;\n` +
      '  *) exit 0 ;;\n' +
      'esac\n',
    { mode: 0o755 }
  );

  fs.writeFileSync(
    target,
    '#!/bin/sh\n' +
      'printf "%s\\n" "$*" >> "$BOUNDED_LOOPS_TEST_LOG"\n' +
      'here=$(dirname "$0")\n' +
      'case "$*" in\n' +
      '  *"import sys"*) exit 0 ;;\n' +
      // An absent engine must LOOK absent: importlib.metadata raises, so the probe exits non-zero.
      `  *"importlib.metadata"*) [ -n "${version}" ] || exit 1; printf '${version}\\n'; exit 0 ;;\n` +
      '  *"bounded_loops.cli"*) exit 0 ;;\n' +
      '  *"-m venv "*)\n' +
      // `$3`, not `${*#-m venv }`: that parameter expansion does not strip a prefix from `$*`, it
      // returns the whole string, so the venv landed in a directory literally named "-m venv ...".
      '    root=$3\n' +
      '    mkdir -p "$root/bin"\n' +
      '    cp "$here/venv-python-template" "$root/bin/python"\n' +
      '    chmod 755 "$root/bin/python"\n' +
      '    exit 0 ;;\n' +
      '  *) exit 1 ;;\n' +
      'esac\n',
    { mode: 0o755 }
  );
  return target;
}

function fakeBl(dir, version) {
  const target = path.join(dir, 'bl');
  fs.writeFileSync(
    target,
    '#!/bin/sh\n' +
      'printf "bl: %s\\n" "$*" >> "$BOUNDED_LOOPS_TEST_LOG"\n' +
      `case "$1" in --version) printf 'bl ${version}\\n'; exit 0 ;; esac\n` +
      'exit 0\n',
    { mode: 0o755 }
  );
  return target;
}

function run(dir, args = ['doctor']) {
  const log = path.join(dir, 'calls.log');
  fs.writeFileSync(log, '');
  const result = spawnSync(process.execPath, [launcher, ...args], {
    env: {
      ...process.env,
      // The temp dir FIRST so the shims shadow any real python3 or bl, but coreutils still
      // resolve. Setting PATH to the temp dir alone also hid dirname, mkdir, cp and chmod, so the
      // shim could not build its fake venv and three tests failed inside the test harness rather
      // than in the launcher — isolation that removed the tools the isolation itself needed.
      PATH: `${dir}:/usr/bin:/bin`,
      BOUNDED_LOOPS_TEST_LOG: log,
      BOUNDED_LOOPS_NPM_HOME: path.join(dir, 'home'), // never the caller's ~/.cache
    },
    encoding: 'utf8',
  });
  return { result, calls: fs.readFileSync(log, 'utf8') };
}

test('an interpreter already at the matching version is used directly', () => {
  const dir = workspace();
  fakePython(dir, { reports: packageVersion });

  const { result, calls } = run(dir);

  assert.equal(result.status, 0, result.stderr);
  assert.match(calls, /-m bounded_loops\.cli doctor/);
  assert.doesNotMatch(calls, /-m venv/, 'must not build a venv when the engine is already present');
  assert.doesNotMatch(calls, /pip install/, 'must not install when the engine is already present');
});

test('a matching bl on PATH is used, and nothing is installed', () => {
  const dir = workspace();
  fakePython(dir, { reports: null }); // the interpreter has no engine
  fakeBl(dir, packageVersion); // but pipx or `uv tool` already put one on PATH

  const { result, calls } = run(dir);

  assert.equal(result.status, 0, result.stderr);
  assert.match(calls, /^bl: doctor$/m, 'the launcher must hand off to the bl on PATH');
  assert.doesNotMatch(calls, /pip install/, 'a working bl on PATH must not trigger an install');
  assert.doesNotMatch(calls, /-m venv/, 'a working bl on PATH must not trigger a venv');
});

test('a bl on PATH at the WRONG version is ignored', () => {
  const dir = workspace();
  fakePython(dir, { reports: null });
  fakeBl(dir, '0.2.1'); // an old global install must never satisfy a newer npx invocation

  const { result, calls } = run(dir);

  assert.equal(result.status, 0, result.stderr);
  assert.doesNotMatch(calls, /^bl: doctor$/m, 'a mismatched bl must not be handed the command');
  assert.match(calls, /-m venv/, 'a mismatched bl must fall through to the private venv');
});

test('with no engine anywhere, the install goes into a private venv and pins the version', () => {
  const dir = workspace();
  fakePython(dir, { reports: null });

  const { result, calls } = run(dir);

  assert.equal(result.status, 0, result.stderr);
  // The venv is created by the DISCOVERED interpreter...
  assert.match(calls, /-m venv/, 'the launcher must create its own virtual environment');
  // ...and every pip install is issued by the VENV's interpreter, never the discovered one. The
  // shim logs venv calls with a "venv: " prefix, so this distinguishes the two.
  assert.match(
    calls,
    new RegExp(`^venv: -m pip install .*bounded-loops==${packageVersion.replace('.', '\\.')}`, 'm'),
    `the install must run inside the venv and pin ${packageVersion}; got:\n${calls}`
  );
  for (const line of calls.split('\n')) {
    if (line.includes('pip install')) {
      assert.ok(
        line.startsWith('venv: '),
        `pip install ran against the discovered interpreter, which PEP 668 refuses: ${line}`
      );
    }
  }
  assert.match(calls, /venv: -m bounded_loops\.cli doctor/, 'the CLI must run from the venv');
});

test('a prepared venv is reused rather than reinstalled', () => {
  const dir = workspace();
  fakePython(dir, { reports: null });

  const first = run(dir);
  assert.equal(first.result.status, 0, first.result.stderr);
  assert.match(first.calls, /pip install/);

  const second = run(dir); // same BOUNDED_LOOPS_NPM_HOME
  assert.equal(second.result.status, 0, second.result.stderr);
  assert.doesNotMatch(second.calls, /pip install/, 'the second run must reuse the venv');
  assert.doesNotMatch(second.calls, /-m venv/, 'the second run must not rebuild the venv');
  assert.match(second.calls, /venv: -m bounded_loops\.cli doctor/);
});

test('a failure to prepare an environment exits non-zero and names a real remedy', () => {
  const dir = workspace();
  // An interpreter that satisfies the version probe and refuses everything else — which is what a
  // Debian box without python3-venv actually does.
  fs.writeFileSync(
    path.join(dir, 'python3'),
    '#!/bin/sh\n' +
      'printf "%s\\n" "$*" >> "$BOUNDED_LOOPS_TEST_LOG"\n' +
      'case "$*" in *"import sys"*) exit 0 ;; esac\n' +
      'exit 1\n',
    { mode: 0o755 }
  );

  const { result } = run(dir);

  assert.equal(result.status, 1, 'a launcher that cannot prepare an engine must not exit 0');
  assert.match(result.stderr, /python3-venv/, 'the remedy must name the missing package');
  assert.match(result.stderr, /pipx install bounded-loops==/, 'and give a command that works');
});

test('the launcher never overrides PEP 668', () => {
  const source = fs.readFileSync(launcher, 'utf8');
  const code = source
    .split('\n')
    .filter((line) => !line.trimStart().startsWith('//'))
    .join('\n');
  assert.doesNotMatch(
    code,
    /--break-system-packages/,
    'that flag exists to override exactly the protection PEP 668 provides'
  );
});
